#include<stdio.h>
#include<ctype.h>
#include<stdlib.h>
#include<string.h>

#include "lexer.h"

int print_options(){
  printf("Your Options Are :\n");
  printf("Press 0 : To exit the program\n");
  printf("Press 1 : For removal of comments\n");
  printf("Press 2 : For printing the token list generated by the lexer\n");
  printf("Press 3 : Verify the syntactic correctness of the input source code and printing the parse tree\n");
  printf("Press 4 : For printing the total time taken by the project code of lexer\n");
}

void print_intro(){
  printf("FIRST and FOLLOW sets automated.\n");
  printf("Only Lexical analyzer module developed\n");
  printf("Both lexical and syntax analysis modules implemented\n");
  printf("Modules compile but give segmentation fault\n");
  printf("Modules work with testcases 2, 3 and 4 only\n");
  printf("Parse tree could not be constructed\n");
  printf("\n");
}


int main(){

}